### ISSUE TITLE
Enpoint POST send null data

### ISSUE THREAD

**Issue by IssamMrini** [codingwithroby/FastAPI-The-Complete-Course#3]
Hello, I followed your tutorial and adapted it to my own way to create my API, but I have an issue when I try to make a POST request. It works, but in the POSTGRESQL database, it only displays the indexed ID, and the rest of the values are null. Can you help me?

![image](https://github.com/codingwithroby/FastAPI-The-Complete-Course/assets/49200875/e6fd595f-aadd-410a-9e5f-3f1d0be015cd)

As you can see the data is null everywhere

![image](https://github.com/codingwithroby/FastAPI-The-Complete-Course/assets/49200875/aee7075a-cfa5-468b-90aa-335f03a51e10)

**Comment by codingwithroby** [comment]
Hi friend!
Would you mind posting this in the Q/A and I will see it there :-)
Cheers,
Eric
